Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-22.04'
  config.vm.hostname = 'dev'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'dev'
    vb.cpus = 4
    vb.memory = 8192
  end
end
